version: '3'
name: bSocial

services:
  main_service:
    build:
      context: ./backend/main_service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - kafka
    container_name: main_service
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./backend/main_service/.env
    environment:
      - PORT=8000
      - JWT_SECRET=ffc632ce-0053-4bab-8077-93a4d14caaaf

  notification_service:
    build:
      context: ./backend/notification_service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - kafka
      - main_service
    container_name: notification_service
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PORT=5000
      - JWT_SECRET=ffc632ce-0053-4bab-8077-93a4d14caaaf

  consumer_service:
    build:
      context: ./backend/consumer_service
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - main_service
      - elasticsearch
    container_name: consumer_service
    restart: always
    ports:
      - "7000:7000"
    volumes:
      - .:/app
    environment:
      - PORT=7000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - main_service
      - notification_service
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  postgres:
    image: postgres
    container_name: bsocial_db
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bsocial
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - kafka_data:/var/lib/kafka/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.13
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]

volumes:
  local_pgdata:
  kafka_data:
  zookeeper_data:
  elasticsearch_data:
